<?php
$sql ="CREATE TABLE IF NOT EXISTS $NomeDaTabela1(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    CELULAR VARCHAR(11) UNIQUE,
    CODIGO VARCHAR(6),
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )ENGINE = InnoDB";
$conexao->query($sql) OR exit($conexao->error);
